#!/bin/sh

/usr/bin/gtk-update-icon-cache -f /usr/share/icons/matefaenza
/usr/bin/gtk-update-icon-cache -f /usr/share/icons/matefaenzadark
/usr/bin/gtk-update-icon-cache -f /usr/share/icons/matefaenzagray

# EOF
